package de.henry.adventofcode.y2022;

import java.util.HashSet;
import java.util.Set;

public class Day09 {

    static final Set<Knot> positions = new HashSet<>();
    static int maxX = 0;
    static int maxY = 0;
    static int minX = 0;
    static int minY = 0;


    public static void main(String[] args) {
        System.out.println("#positions visited (rope length 1): " + process(INPUT, 1));
        System.out.println("#positions visited (rope length 10): " + process(INPUT, 10));
    }
    static int process(String pInput, int pLength) {
        reset();
        Knot H = new Knot(0, 0, pLength-1);
        for (String instruction : pInput.split("\n")) {
            H.move(instruction);
        }
        drawMap();
        return positions.size();
    }

    private static void drawMap() {
        for (int y=maxY; y >= minY; y--) {
            for (int x=minX; x <= maxX; x++) {
                System.out.print(positions.contains(new Knot(x,y,0)) ? '#' : '.');
            }
            System.out.println();
        }
        System.out.println();
    }

    private static void reset() {
        positions.clear();
        maxX = 0;
        maxY = 0;

    }

    static class Knot {
        int x;
        int y;

        Knot follower;

        Knot(int pX, int pY, int pRemainingLength) {
            x = pX;
            y = pY;
            if (pRemainingLength > 0) {
                follower = new Knot(pX, pY, pRemainingLength - 1);
            }
        }

        Knot(Knot p) {
            x = p.x;
            y = p.y;
            // do not copy follower!
        }

        void move(String pInstruction) {
            char dir = pInstruction.charAt(0);
            int steps = Integer.parseInt(pInstruction.substring(2));
            for (int i = 0; i < steps; i++) {
                switch (dir) {
                    case 'R':
                        x++;
                        break;
                    case 'L':
                        x--;
                        break;
                    case 'U':
                        y++;
                        break;
                    case 'D':
                        y--;
                        break;
                    default:
                        throw new RuntimeException("illegal instruction: " + pInstruction);
                }
                if (follower != null) {
                    follower.follow(this);
                }
            }
        }
        void follow(Knot pHead) {
            if (pHead.x - x > 1) {
                x = pHead.x - 1;
                y = pHead.y;
            } else if (pHead.x - x < -1) {
                x = pHead.x + 1;
                y = pHead.y;
            } else if (pHead.y - y > 1) {
                y = pHead.y - 1;
                x = pHead.x;
            } else if (pHead.y - y < -1) {
                y = pHead.y + 1;
                x = pHead.x;
            }
            if (follower != null) {
                follower.follow(this);
            } else {
                // mark new Position of the tail
                positions.add(new Knot(this));
                if (x > maxX) maxX = x;
                if (y > maxY) maxY = y;
                if (x < minX) minX = x;
                if (y < minY) minY = y;
            }
        }

        @Override
        public boolean equals(Object obj) {
            if (obj instanceof Knot) {
                return x == ((Knot) obj).x && y == ((Knot) obj).y;
            }
            return false;
        }

        @Override
        public int hashCode() {
            return 31 * x + y;
        }
    }

    private static final String INPUT =
            "R 2\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "U 3\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "U 3\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "R 3\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 3\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "R 3\n" +
                    "U 3\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "D 3\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "L 3\n" +
                    "U 2\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "R 3\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "U 1\n" +
                    "R 4\n" +
                    "D 1\n" +
                    "R 4\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "U 4\n" +
                    "D 1\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "U 4\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "R 2\n" +
                    "L 4\n" +
                    "U 1\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "D 3\n" +
                    "U 4\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "D 3\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "R 4\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "D 4\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "R 3\n" +
                    "D 1\n" +
                    "U 4\n" +
                    "R 4\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "U 4\n" +
                    "R 2\n" +
                    "U 3\n" +
                    "R 4\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "U 4\n" +
                    "R 3\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "U 4\n" +
                    "D 4\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "L 4\n" +
                    "U 4\n" +
                    "R 4\n" +
                    "U 3\n" +
                    "R 3\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "L 2\n" +
                    "U 3\n" +
                    "L 2\n" +
                    "R 3\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "L 4\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 5\n" +
                    "D 5\n" +
                    "R 5\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "U 2\n" +
                    "D 5\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "R 4\n" +
                    "U 5\n" +
                    "L 2\n" +
                    "U 5\n" +
                    "R 4\n" +
                    "L 3\n" +
                    "R 4\n" +
                    "U 5\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "L 4\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "R 5\n" +
                    "D 5\n" +
                    "U 3\n" +
                    "R 4\n" +
                    "U 4\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "L 5\n" +
                    "D 2\n" +
                    "R 4\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "D 4\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "L 4\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "U 5\n" +
                    "R 5\n" +
                    "U 5\n" +
                    "L 1\n" +
                    "U 5\n" +
                    "D 5\n" +
                    "R 5\n" +
                    "L 2\n" +
                    "U 5\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "U 4\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "L 4\n" +
                    "R 3\n" +
                    "U 3\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "R 4\n" +
                    "L 4\n" +
                    "U 4\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "U 3\n" +
                    "D 1\n" +
                    "L 3\n" +
                    "R 4\n" +
                    "D 5\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "L 5\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "U 2\n" +
                    "D 5\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "U 6\n" +
                    "L 6\n" +
                    "R 5\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "D 4\n" +
                    "U 3\n" +
                    "L 5\n" +
                    "R 4\n" +
                    "D 6\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "D 6\n" +
                    "R 2\n" +
                    "D 4\n" +
                    "U 3\n" +
                    "D 4\n" +
                    "L 5\n" +
                    "U 1\n" +
                    "D 6\n" +
                    "R 6\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "L 6\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "D 6\n" +
                    "R 5\n" +
                    "D 4\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "L 5\n" +
                    "U 3\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "U 3\n" +
                    "D 5\n" +
                    "L 3\n" +
                    "R 6\n" +
                    "U 2\n" +
                    "R 6\n" +
                    "L 3\n" +
                    "U 1\n" +
                    "D 3\n" +
                    "U 1\n" +
                    "R 3\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "R 2\n" +
                    "L 3\n" +
                    "U 5\n" +
                    "R 6\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "U 5\n" +
                    "R 6\n" +
                    "D 5\n" +
                    "L 6\n" +
                    "R 5\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "U 6\n" +
                    "L 6\n" +
                    "D 3\n" +
                    "R 6\n" +
                    "L 4\n" +
                    "R 1\n" +
                    "U 4\n" +
                    "D 5\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 4\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "D 6\n" +
                    "L 6\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "U 4\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "U 5\n" +
                    "R 2\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "L 5\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "D 4\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "U 6\n" +
                    "R 1\n" +
                    "U 6\n" +
                    "R 4\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "L 6\n" +
                    "R 6\n" +
                    "U 4\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "L 7\n" +
                    "R 4\n" +
                    "L 6\n" +
                    "R 4\n" +
                    "L 7\n" +
                    "U 4\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "R 7\n" +
                    "L 2\n" +
                    "R 6\n" +
                    "L 2\n" +
                    "R 6\n" +
                    "D 6\n" +
                    "U 3\n" +
                    "D 7\n" +
                    "R 3\n" +
                    "U 6\n" +
                    "R 3\n" +
                    "D 6\n" +
                    "U 4\n" +
                    "D 3\n" +
                    "L 5\n" +
                    "U 5\n" +
                    "L 3\n" +
                    "R 3\n" +
                    "D 7\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "R 7\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "L 6\n" +
                    "R 7\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "D 7\n" +
                    "R 4\n" +
                    "U 5\n" +
                    "L 3\n" +
                    "R 3\n" +
                    "U 6\n" +
                    "R 6\n" +
                    "U 1\n" +
                    "D 5\n" +
                    "U 4\n" +
                    "L 1\n" +
                    "U 6\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "D 6\n" +
                    "U 7\n" +
                    "D 6\n" +
                    "U 3\n" +
                    "R 7\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "R 4\n" +
                    "L 6\n" +
                    "U 4\n" +
                    "D 5\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "D 7\n" +
                    "L 4\n" +
                    "R 2\n" +
                    "U 6\n" +
                    "R 4\n" +
                    "D 1\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "R 3\n" +
                    "D 1\n" +
                    "L 4\n" +
                    "R 5\n" +
                    "L 4\n" +
                    "U 1\n" +
                    "D 6\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "L 4\n" +
                    "R 2\n" +
                    "U 5\n" +
                    "L 6\n" +
                    "R 4\n" +
                    "U 6\n" +
                    "L 4\n" +
                    "U 5\n" +
                    "D 1\n" +
                    "L 4\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "D 6\n" +
                    "R 1\n" +
                    "L 5\n" +
                    "D 6\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "L 6\n" +
                    "D 1\n" +
                    "U 7\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "D 8\n" +
                    "R 2\n" +
                    "D 3\n" +
                    "L 4\n" +
                    "R 3\n" +
                    "U 7\n" +
                    "R 8\n" +
                    "D 3\n" +
                    "R 2\n" +
                    "D 8\n" +
                    "L 4\n" +
                    "R 4\n" +
                    "L 7\n" +
                    "R 1\n" +
                    "U 8\n" +
                    "R 7\n" +
                    "U 2\n" +
                    "D 5\n" +
                    "L 6\n" +
                    "D 8\n" +
                    "U 3\n" +
                    "L 5\n" +
                    "R 4\n" +
                    "D 1\n" +
                    "R 4\n" +
                    "L 6\n" +
                    "U 1\n" +
                    "R 5\n" +
                    "L 8\n" +
                    "D 6\n" +
                    "L 3\n" +
                    "D 6\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "D 4\n" +
                    "R 6\n" +
                    "D 6\n" +
                    "U 6\n" +
                    "D 5\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "U 6\n" +
                    "D 5\n" +
                    "L 6\n" +
                    "R 8\n" +
                    "D 6\n" +
                    "R 6\n" +
                    "U 5\n" +
                    "D 6\n" +
                    "U 3\n" +
                    "D 7\n" +
                    "L 8\n" +
                    "R 2\n" +
                    "D 8\n" +
                    "L 5\n" +
                    "R 7\n" +
                    "L 5\n" +
                    "U 5\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "R 3\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "D 8\n" +
                    "R 8\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "D 4\n" +
                    "U 6\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 5\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "D 6\n" +
                    "R 2\n" +
                    "U 5\n" +
                    "L 7\n" +
                    "D 7\n" +
                    "L 7\n" +
                    "R 1\n" +
                    "D 4\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "R 3\n" +
                    "L 8\n" +
                    "D 8\n" +
                    "R 4\n" +
                    "U 7\n" +
                    "R 2\n" +
                    "L 6\n" +
                    "D 5\n" +
                    "U 4\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "U 5\n" +
                    "D 5\n" +
                    "U 1\n" +
                    "D 7\n" +
                    "L 7\n" +
                    "U 7\n" +
                    "D 4\n" +
                    "U 3\n" +
                    "L 7\n" +
                    "U 6\n" +
                    "L 6\n" +
                    "R 5\n" +
                    "U 5\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "U 6\n" +
                    "L 6\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "U 5\n" +
                    "D 1\n" +
                    "U 8\n" +
                    "D 1\n" +
                    "L 6\n" +
                    "D 5\n" +
                    "L 8\n" +
                    "R 6\n" +
                    "L 9\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "R 9\n" +
                    "U 1\n" +
                    "L 3\n" +
                    "R 8\n" +
                    "U 6\n" +
                    "R 8\n" +
                    "L 6\n" +
                    "R 2\n" +
                    "L 3\n" +
                    "R 7\n" +
                    "D 6\n" +
                    "R 3\n" +
                    "U 2\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "L 4\n" +
                    "R 6\n" +
                    "L 9\n" +
                    "D 4\n" +
                    "L 7\n" +
                    "U 2\n" +
                    "D 4\n" +
                    "L 8\n" +
                    "U 7\n" +
                    "R 7\n" +
                    "U 5\n" +
                    "D 4\n" +
                    "U 1\n" +
                    "L 8\n" +
                    "R 4\n" +
                    "D 5\n" +
                    "R 3\n" +
                    "D 5\n" +
                    "U 9\n" +
                    "D 6\n" +
                    "R 3\n" +
                    "D 6\n" +
                    "L 7\n" +
                    "U 7\n" +
                    "L 1\n" +
                    "R 3\n" +
                    "U 2\n" +
                    "L 4\n" +
                    "R 7\n" +
                    "L 9\n" +
                    "D 3\n" +
                    "L 6\n" +
                    "D 4\n" +
                    "R 6\n" +
                    "D 2\n" +
                    "L 6\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "L 7\n" +
                    "D 4\n" +
                    "R 9\n" +
                    "D 7\n" +
                    "U 1\n" +
                    "L 3\n" +
                    "R 9\n" +
                    "L 7\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "D 5\n" +
                    "L 9\n" +
                    "D 6\n" +
                    "R 5\n" +
                    "D 8\n" +
                    "U 7\n" +
                    "D 5\n" +
                    "R 1\n" +
                    "D 4\n" +
                    "R 5\n" +
                    "D 3\n" +
                    "R 4\n" +
                    "D 5\n" +
                    "U 7\n" +
                    "D 5\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "L 8\n" +
                    "U 1\n" +
                    "R 5\n" +
                    "U 3\n" +
                    "L 7\n" +
                    "D 5\n" +
                    "R 4\n" +
                    "D 6\n" +
                    "L 5\n" +
                    "D 7\n" +
                    "R 5\n" +
                    "D 7\n" +
                    "U 7\n" +
                    "R 8\n" +
                    "U 6\n" +
                    "D 1\n" +
                    "U 4\n" +
                    "R 5\n" +
                    "U 4\n" +
                    "D 5\n" +
                    "U 2\n" +
                    "D 5\n" +
                    "L 4\n" +
                    "D 1\n" +
                    "R 7\n" +
                    "L 10\n" +
                    "D 4\n" +
                    "R 10\n" +
                    "U 8\n" +
                    "D 5\n" +
                    "L 4\n" +
                    "R 3\n" +
                    "D 10\n" +
                    "U 1\n" +
                    "R 8\n" +
                    "L 4\n" +
                    "R 7\n" +
                    "L 5\n" +
                    "U 8\n" +
                    "L 3\n" +
                    "U 6\n" +
                    "R 5\n" +
                    "D 4\n" +
                    "L 7\n" +
                    "D 9\n" +
                    "R 10\n" +
                    "U 9\n" +
                    "L 7\n" +
                    "R 1\n" +
                    "D 9\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "L 7\n" +
                    "D 3\n" +
                    "U 7\n" +
                    "L 4\n" +
                    "D 2\n" +
                    "R 5\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "R 9\n" +
                    "U 8\n" +
                    "L 4\n" +
                    "D 7\n" +
                    "R 5\n" +
                    "U 9\n" +
                    "L 10\n" +
                    "U 9\n" +
                    "R 4\n" +
                    "D 6\n" +
                    "U 9\n" +
                    "R 8\n" +
                    "D 3\n" +
                    "R 8\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "R 7\n" +
                    "L 9\n" +
                    "D 3\n" +
                    "U 8\n" +
                    "L 8\n" +
                    "R 1\n" +
                    "L 9\n" +
                    "D 9\n" +
                    "U 9\n" +
                    "L 9\n" +
                    "R 8\n" +
                    "L 5\n" +
                    "D 6\n" +
                    "L 5\n" +
                    "U 10\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "R 7\n" +
                    "D 7\n" +
                    "U 5\n" +
                    "L 1\n" +
                    "D 5\n" +
                    "U 8\n" +
                    "D 10\n" +
                    "U 10\n" +
                    "R 2\n" +
                    "L 4\n" +
                    "R 5\n" +
                    "U 9\n" +
                    "L 4\n" +
                    "U 10\n" +
                    "D 5\n" +
                    "U 7\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "R 7\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "L 9\n" +
                    "U 5\n" +
                    "L 10\n" +
                    "U 7\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "U 7\n" +
                    "L 4\n" +
                    "U 6\n" +
                    "D 9\n" +
                    "U 6\n" +
                    "R 4\n" +
                    "L 6\n" +
                    "R 4\n" +
                    "L 8\n" +
                    "R 4\n" +
                    "D 4\n" +
                    "L 11\n" +
                    "U 7\n" +
                    "R 6\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "R 8\n" +
                    "D 2\n" +
                    "L 7\n" +
                    "U 9\n" +
                    "L 9\n" +
                    "D 1\n" +
                    "U 9\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "L 6\n" +
                    "R 10\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "L 9\n" +
                    "R 8\n" +
                    "L 3\n" +
                    "R 6\n" +
                    "L 9\n" +
                    "U 1\n" +
                    "R 3\n" +
                    "D 7\n" +
                    "U 10\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "D 5\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "L 6\n" +
                    "D 11\n" +
                    "R 11\n" +
                    "L 3\n" +
                    "D 6\n" +
                    "R 6\n" +
                    "D 8\n" +
                    "L 6\n" +
                    "R 5\n" +
                    "U 9\n" +
                    "D 7\n" +
                    "R 2\n" +
                    "U 6\n" +
                    "R 4\n" +
                    "U 11\n" +
                    "D 2\n" +
                    "R 4\n" +
                    "L 11\n" +
                    "D 1\n" +
                    "R 6\n" +
                    "D 8\n" +
                    "L 11\n" +
                    "U 7\n" +
                    "D 6\n" +
                    "R 6\n" +
                    "L 4\n" +
                    "R 5\n" +
                    "L 4\n" +
                    "R 3\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "U 6\n" +
                    "D 9\n" +
                    "R 11\n" +
                    "U 4\n" +
                    "L 10\n" +
                    "R 5\n" +
                    "L 2\n" +
                    "U 7\n" +
                    "R 4\n" +
                    "L 2\n" +
                    "R 9\n" +
                    "D 1\n" +
                    "R 7\n" +
                    "L 11\n" +
                    "R 3\n" +
                    "L 4\n" +
                    "D 7\n" +
                    "L 10\n" +
                    "D 3\n" +
                    "U 11\n" +
                    "L 6\n" +
                    "U 9\n" +
                    "R 8\n" +
                    "U 3\n" +
                    "D 10\n" +
                    "U 8\n" +
                    "D 5\n" +
                    "R 1\n" +
                    "L 5\n" +
                    "R 11\n" +
                    "L 11\n" +
                    "R 9\n" +
                    "U 7\n" +
                    "R 1\n" +
                    "L 9\n" +
                    "D 3\n" +
                    "L 9\n" +
                    "U 1\n" +
                    "L 5\n" +
                    "D 10\n" +
                    "L 8\n" +
                    "R 4\n" +
                    "D 10\n" +
                    "R 4\n" +
                    "D 5\n" +
                    "L 12\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "U 9\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "D 6\n" +
                    "R 10\n" +
                    "U 3\n" +
                    "R 8\n" +
                    "L 3\n" +
                    "R 11\n" +
                    "L 5\n" +
                    "U 11\n" +
                    "D 5\n" +
                    "U 4\n" +
                    "L 3\n" +
                    "D 11\n" +
                    "R 5\n" +
                    "D 4\n" +
                    "L 11\n" +
                    "D 2\n" +
                    "U 9\n" +
                    "R 10\n" +
                    "L 10\n" +
                    "R 7\n" +
                    "D 11\n" +
                    "R 1\n" +
                    "U 9\n" +
                    "L 4\n" +
                    "U 3\n" +
                    "L 7\n" +
                    "U 1\n" +
                    "L 10\n" +
                    "R 7\n" +
                    "L 11\n" +
                    "U 11\n" +
                    "R 9\n" +
                    "L 4\n" +
                    "R 2\n" +
                    "L 10\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "R 11\n" +
                    "D 5\n" +
                    "U 1\n" +
                    "R 12\n" +
                    "D 9\n" +
                    "R 4\n" +
                    "L 9\n" +
                    "D 8\n" +
                    "R 7\n" +
                    "L 2\n" +
                    "D 7\n" +
                    "R 8\n" +
                    "D 5\n" +
                    "U 7\n" +
                    "L 12\n" +
                    "R 6\n" +
                    "U 3\n" +
                    "R 11\n" +
                    "L 9\n" +
                    "R 8\n" +
                    "U 8\n" +
                    "R 4\n" +
                    "L 10\n" +
                    "U 4\n" +
                    "R 7\n" +
                    "D 10\n" +
                    "U 4\n" +
                    "L 11\n" +
                    "D 1\n" +
                    "U 6\n" +
                    "L 4\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "L 7\n" +
                    "U 6\n" +
                    "R 3\n" +
                    "U 9\n" +
                    "L 8\n" +
                    "R 8\n" +
                    "U 10\n" +
                    "R 8\n" +
                    "U 9\n" +
                    "R 4\n" +
                    "U 6\n" +
                    "R 12\n" +
                    "U 8\n" +
                    "L 10\n" +
                    "D 8\n" +
                    "R 10\n" +
                    "L 1\n" +
                    "U 5\n" +
                    "D 7\n" +
                    "L 10\n" +
                    "R 9\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "R 12\n" +
                    "L 1\n" +
                    "D 12\n" +
                    "U 8\n" +
                    "R 4\n" +
                    "L 12\n" +
                    "R 7\n" +
                    "D 4\n" +
                    "U 10\n" +
                    "L 11\n" +
                    "U 8\n" +
                    "L 4\n" +
                    "R 1\n" +
                    "L 10\n" +
                    "U 12\n" +
                    "R 5\n" +
                    "U 2\n" +
                    "R 5\n" +
                    "L 11\n" +
                    "U 6\n" +
                    "D 8\n" +
                    "L 11\n" +
                    "D 1\n" +
                    "U 13\n" +
                    "D 8\n" +
                    "R 4\n" +
                    "D 6\n" +
                    "R 11\n" +
                    "L 10\n" +
                    "R 6\n" +
                    "L 4\n" +
                    "D 7\n" +
                    "U 10\n" +
                    "R 1\n" +
                    "L 8\n" +
                    "U 7\n" +
                    "D 1\n" +
                    "R 5\n" +
                    "D 5\n" +
                    "L 1\n" +
                    "U 7\n" +
                    "L 2\n" +
                    "U 4\n" +
                    "D 13\n" +
                    "R 10\n" +
                    "U 11\n" +
                    "D 13\n" +
                    "L 8\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "L 9\n" +
                    "R 10\n" +
                    "U 10\n" +
                    "D 3\n" +
                    "U 13\n" +
                    "R 4\n" +
                    "D 9\n" +
                    "L 9\n" +
                    "U 10\n" +
                    "D 7\n" +
                    "U 4\n" +
                    "R 13\n" +
                    "U 6\n" +
                    "D 1\n" +
                    "U 8\n" +
                    "L 1\n" +
                    "R 13\n" +
                    "U 3\n" +
                    "L 11\n" +
                    "U 12\n" +
                    "R 9\n" +
                    "L 8\n" +
                    "R 9\n" +
                    "L 2\n" +
                    "R 5\n" +
                    "L 7\n" +
                    "D 11\n" +
                    "L 8\n" +
                    "R 13\n" +
                    "D 10\n" +
                    "U 4\n" +
                    "R 5\n" +
                    "D 13\n" +
                    "L 2\n" +
                    "R 9\n" +
                    "L 5\n" +
                    "D 8\n" +
                    "L 13\n" +
                    "U 13\n" +
                    "D 1\n" +
                    "L 4\n" +
                    "U 5\n" +
                    "D 13\n" +
                    "R 2\n" +
                    "L 6\n" +
                    "D 12\n" +
                    "L 4\n" +
                    "U 5\n" +
                    "R 10\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "R 8\n" +
                    "U 10\n" +
                    "L 9\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "U 12\n" +
                    "D 6\n" +
                    "U 13\n" +
                    "L 5\n" +
                    "D 6\n" +
                    "U 14\n" +
                    "L 13\n" +
                    "U 7\n" +
                    "D 2\n" +
                    "U 8\n" +
                    "L 13\n" +
                    "R 10\n" +
                    "U 12\n" +
                    "R 5\n" +
                    "D 10\n" +
                    "U 5\n" +
                    "R 8\n" +
                    "D 2\n" +
                    "L 4\n" +
                    "R 9\n" +
                    "U 11\n" +
                    "R 10\n" +
                    "U 7\n" +
                    "L 14\n" +
                    "R 14\n" +
                    "U 14\n" +
                    "D 13\n" +
                    "U 9\n" +
                    "D 13\n" +
                    "R 5\n" +
                    "D 14\n" +
                    "U 11\n" +
                    "R 7\n" +
                    "U 11\n" +
                    "D 8\n" +
                    "R 11\n" +
                    "U 2\n" +
                    "R 4\n" +
                    "U 6\n" +
                    "L 11\n" +
                    "U 6\n" +
                    "R 8\n" +
                    "L 6\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "D 5\n" +
                    "R 2\n" +
                    "U 11\n" +
                    "D 9\n" +
                    "R 14\n" +
                    "L 13\n" +
                    "U 4\n" +
                    "R 8\n" +
                    "L 4\n" +
                    "R 8\n" +
                    "D 14\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "D 4\n" +
                    "L 4\n" +
                    "D 11\n" +
                    "U 4\n" +
                    "L 5\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "D 8\n" +
                    "L 11\n" +
                    "R 7\n" +
                    "U 13\n" +
                    "L 9\n" +
                    "R 14\n" +
                    "D 1\n" +
                    "R 8\n" +
                    "U 10\n" +
                    "R 9\n" +
                    "L 5\n" +
                    "U 7\n" +
                    "L 2\n" +
                    "R 14\n" +
                    "D 6\n" +
                    "U 12\n" +
                    "D 10\n" +
                    "U 1\n" +
                    "L 14\n" +
                    "D 2\n" +
                    "R 14\n" +
                    "U 6\n" +
                    "L 7\n" +
                    "U 3\n" +
                    "L 6\n" +
                    "U 7\n" +
                    "L 6\n" +
                    "D 7\n" +
                    "R 9\n" +
                    "U 11\n" +
                    "D 9\n" +
                    "U 7\n" +
                    "R 14\n" +
                    "U 8\n" +
                    "L 4\n" +
                    "U 8\n" +
                    "R 1\n" +
                    "L 12\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "D 11\n" +
                    "R 8\n" +
                    "D 9\n" +
                    "U 9\n" +
                    "D 3\n" +
                    "U 5\n" +
                    "D 8\n" +
                    "U 8\n" +
                    "D 1\n" +
                    "L 12\n" +
                    "U 15\n" +
                    "L 2\n" +
                    "D 13\n" +
                    "R 4\n" +
                    "U 2\n" +
                    "R 7\n" +
                    "U 1\n" +
                    "R 4\n" +
                    "L 4\n" +
                    "D 1\n" +
                    "R 5\n" +
                    "D 9\n" +
                    "L 12\n" +
                    "D 11\n" +
                    "R 4\n" +
                    "D 14\n" +
                    "L 1\n" +
                    "U 13\n" +
                    "R 6\n" +
                    "D 13\n" +
                    "U 6\n" +
                    "D 10\n" +
                    "L 3\n" +
                    "U 8\n" +
                    "L 12\n" +
                    "D 1\n" +
                    "L 6\n" +
                    "D 5\n" +
                    "R 12\n" +
                    "D 11\n" +
                    "L 10\n" +
                    "U 14\n" +
                    "R 2\n" +
                    "D 4\n" +
                    "U 15\n" +
                    "D 10\n" +
                    "R 12\n" +
                    "D 7\n" +
                    "U 14\n" +
                    "L 14\n" +
                    "R 7\n" +
                    "U 15\n" +
                    "D 5\n" +
                    "U 13\n" +
                    "R 5\n" +
                    "U 6\n" +
                    "D 10\n" +
                    "L 12\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "R 14\n" +
                    "D 9\n" +
                    "U 7\n" +
                    "L 5\n" +
                    "D 9\n" +
                    "R 14\n" +
                    "L 12\n" +
                    "R 2\n" +
                    "L 6\n" +
                    "R 13\n" +
                    "U 11\n" +
                    "L 10\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "L 5\n" +
                    "R 8\n" +
                    "L 7\n" +
                    "U 7\n" +
                    "L 15\n" +
                    "R 5\n" +
                    "U 11\n" +
                    "L 10\n" +
                    "R 11\n" +
                    "L 5\n" +
                    "U 6\n" +
                    "R 4\n" +
                    "D 14\n" +
                    "U 13\n" +
                    "R 8\n" +
                    "L 10\n" +
                    "R 5\n" +
                    "U 8\n" +
                    "L 14\n" +
                    "D 6\n" +
                    "L 5\n" +
                    "D 7\n" +
                    "R 11\n" +
                    "L 15\n" +
                    "R 6\n" +
                    "L 15\n" +
                    "D 7\n" +
                    "R 9\n" +
                    "D 12\n" +
                    "L 3\n" +
                    "R 11\n" +
                    "L 10\n" +
                    "D 6\n" +
                    "L 6\n" +
                    "U 9\n" +
                    "L 10\n" +
                    "R 11\n" +
                    "D 7\n" +
                    "L 13\n" +
                    "D 11\n" +
                    "R 1\n" +
                    "U 4\n" +
                    "L 2\n" +
                    "R 4\n" +
                    "D 6\n" +
                    "U 8\n" +
                    "R 15\n" +
                    "L 10\n" +
                    "U 16\n" +
                    "R 10\n" +
                    "D 1\n" +
                    "U 14\n" +
                    "L 6\n" +
                    "D 1\n" +
                    "R 8\n" +
                    "U 6\n" +
                    "D 11\n" +
                    "L 9\n" +
                    "R 13\n" +
                    "U 12\n" +
                    "R 8\n" +
                    "D 7\n" +
                    "R 15\n" +
                    "U 1\n" +
                    "D 3\n" +
                    "U 13\n" +
                    "L 11\n" +
                    "D 6\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 14\n" +
                    "U 10\n" +
                    "R 8\n" +
                    "L 9\n" +
                    "D 12\n" +
                    "U 16\n" +
                    "L 8\n" +
                    "U 10\n" +
                    "D 8\n" +
                    "U 2\n" +
                    "L 4\n" +
                    "D 4\n" +
                    "L 3\n" +
                    "R 3\n" +
                    "D 5\n" +
                    "U 2\n" +
                    "L 11\n" +
                    "D 16\n" +
                    "L 15\n" +
                    "R 15\n" +
                    "L 12\n" +
                    "D 8\n" +
                    "R 1\n" +
                    "D 11\n" +
                    "U 5\n" +
                    "R 10\n" +
                    "U 12\n" +
                    "D 9\n" +
                    "L 16\n" +
                    "U 10\n" +
                    "L 13\n" +
                    "R 10\n" +
                    "L 4\n" +
                    "R 6\n" +
                    "D 15\n" +
                    "U 12\n" +
                    "L 2\n" +
                    "R 15\n" +
                    "U 5\n" +
                    "R 1\n" +
                    "L 8\n" +
                    "D 6\n" +
                    "L 7\n" +
                    "D 13\n" +
                    "L 7\n" +
                    "D 10\n" +
                    "R 11\n" +
                    "L 14\n" +
                    "U 12\n" +
                    "D 7\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "R 14\n" +
                    "U 8\n" +
                    "D 7\n" +
                    "L 4\n" +
                    "D 15\n" +
                    "R 8\n" +
                    "U 1\n" +
                    "L 4\n" +
                    "R 12\n" +
                    "U 6\n" +
                    "L 13\n" +
                    "R 14\n" +
                    "U 3\n" +
                    "L 4\n" +
                    "D 9\n" +
                    "R 6\n" +
                    "U 5\n" +
                    "R 14\n" +
                    "L 6\n" +
                    "D 5\n" +
                    "U 6\n" +
                    "R 14\n" +
                    "L 10\n" +
                    "U 13\n" +
                    "L 16\n" +
                    "R 15\n" +
                    "L 12\n" +
                    "U 10\n" +
                    "L 2\n" +
                    "D 8\n" +
                    "L 7\n" +
                    "D 16\n" +
                    "L 17\n" +
                    "U 16\n" +
                    "R 13\n" +
                    "D 6\n" +
                    "U 8\n" +
                    "L 13\n" +
                    "D 9\n" +
                    "U 13\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "U 12\n" +
                    "D 6\n" +
                    "L 8\n" +
                    "U 15\n" +
                    "R 6\n" +
                    "L 14\n" +
                    "U 15\n" +
                    "D 4\n" +
                    "U 9\n" +
                    "R 6\n" +
                    "D 8\n" +
                    "L 10\n" +
                    "D 3\n" +
                    "R 12\n" +
                    "L 10\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "U 17\n" +
                    "D 16\n" +
                    "R 5\n" +
                    "L 13\n" +
                    "R 12\n" +
                    "L 4\n" +
                    "U 4\n" +
                    "L 12\n" +
                    "U 3\n" +
                    "L 15\n" +
                    "U 10\n" +
                    "L 5\n" +
                    "U 2\n" +
                    "D 13\n" +
                    "R 10\n" +
                    "U 7\n" +
                    "R 9\n" +
                    "D 7\n" +
                    "R 12\n" +
                    "U 14\n" +
                    "L 7\n" +
                    "R 10\n" +
                    "D 11\n" +
                    "U 8\n" +
                    "L 5\n" +
                    "R 4\n" +
                    "U 17\n" +
                    "L 12\n" +
                    "R 6\n" +
                    "L 17\n" +
                    "D 11\n" +
                    "R 17\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "U 14\n" +
                    "D 17\n" +
                    "L 2\n" +
                    "D 14\n" +
                    "R 14\n" +
                    "L 1\n" +
                    "U 5\n" +
                    "D 8\n" +
                    "U 1\n" +
                    "R 12\n" +
                    "U 8\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "D 8\n" +
                    "R 5\n" +
                    "U 9\n" +
                    "D 13\n" +
                    "U 15\n" +
                    "D 3\n" +
                    "R 15\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "U 8\n" +
                    "R 1\n" +
                    "L 17\n" +
                    "U 16\n" +
                    "L 10\n" +
                    "D 2\n" +
                    "R 6\n" +
                    "L 11\n" +
                    "D 14\n" +
                    "R 3\n" +
                    "L 15\n" +
                    "U 16\n" +
                    "R 12\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "R 7\n" +
                    "L 4\n" +
                    "D 12\n" +
                    "U 12\n" +
                    "L 12\n" +
                    "U 15\n" +
                    "R 4\n" +
                    "U 8\n" +
                    "R 12\n" +
                    "L 5\n" +
                    "R 3\n" +
                    "L 5\n" +
                    "R 18\n" +
                    "L 4\n" +
                    "D 14\n" +
                    "R 4\n" +
                    "L 17\n" +
                    "R 18\n" +
                    "U 9\n" +
                    "D 18\n" +
                    "R 4\n" +
                    "U 13\n" +
                    "R 3\n" +
                    "D 6\n" +
                    "R 15\n" +
                    "L 1\n" +
                    "U 5\n" +
                    "L 3\n" +
                    "U 2\n" +
                    "R 15\n" +
                    "U 8\n" +
                    "L 7\n" +
                    "D 9\n" +
                    "L 15\n" +
                    "U 13\n" +
                    "L 17\n" +
                    "D 17\n" +
                    "R 15\n" +
                    "D 15\n" +
                    "L 14\n" +
                    "D 15\n" +
                    "R 16\n" +
                    "U 3\n" +
                    "D 6\n" +
                    "L 1\n" +
                    "R 14\n" +
                    "U 16\n" +
                    "L 7\n" +
                    "U 2\n" +
                    "L 14\n" +
                    "D 5\n" +
                    "L 6\n" +
                    "D 12\n" +
                    "R 18\n" +
                    "U 16\n" +
                    "D 7\n" +
                    "L 18\n" +
                    "D 10\n" +
                    "R 1\n" +
                    "L 8\n" +
                    "R 16\n" +
                    "L 5\n" +
                    "U 4\n" +
                    "R 18\n" +
                    "D 18\n" +
                    "R 5\n" +
                    "D 10\n" +
                    "L 18\n" +
                    "R 8\n" +
                    "L 2\n" +
                    "R 13\n" +
                    "L 16\n" +
                    "D 16\n" +
                    "U 17\n" +
                    "L 2\n" +
                    "R 5\n" +
                    "L 12\n" +
                    "D 10\n" +
                    "L 10\n" +
                    "D 6\n" +
                    "R 12\n" +
                    "L 17\n" +
                    "R 8\n" +
                    "L 14\n" +
                    "R 15\n" +
                    "L 18\n" +
                    "D 5\n" +
                    "R 1\n" +
                    "L 8\n" +
                    "U 13\n" +
                    "R 9\n" +
                    "U 14\n" +
                    "L 18\n" +
                    "U 4\n" +
                    "D 16\n" +
                    "L 7\n" +
                    "U 16\n" +
                    "L 14\n" +
                    "D 18\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "R 11\n" +
                    "D 3\n" +
                    "U 12\n" +
                    "D 11\n" +
                    "U 2\n" +
                    "L 12\n" +
                    "U 7\n" +
                    "D 2\n" +
                    "R 8\n" +
                    "D 1\n" +
                    "U 9\n" +
                    "L 5\n" +
                    "D 14\n" +
                    "L 9\n" +
                    "D 5\n" +
                    "L 18\n" +
                    "D 16\n" +
                    "U 3\n" +
                    "R 13\n" +
                    "D 16\n" +
                    "R 18\n" +
                    "D 10\n" +
                    "L 4\n" +
                    "R 2\n" +
                    "L 5\n" +
                    "D 13\n" +
                    "L 15\n" +
                    "U 16\n" +
                    "R 9\n" +
                    "D 15\n" +
                    "R 5\n" +
                    "L 3\n" +
                    "U 5\n" +
                    "R 10\n" +
                    "U 3\n" +
                    "L 11\n" +
                    "R 14\n" +
                    "L 4\n" +
                    "D 7\n" +
                    "R 11\n" +
                    "D 12\n" +
                    "L 14\n" +
                    "R 13\n" +
                    "U 15\n" +
                    "R 14\n" +
                    "D 2\n" +
                    "R 16\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "L 17\n" +
                    "D 11\n" +
                    "U 10\n" +
                    "L 2\n" +
                    "U 12\n" +
                    "D 3\n" +
                    "L 5\n" +
                    "D 9\n" +
                    "U 7\n" +
                    "D 14\n" +
                    "R 5\n" +
                    "L 14\n" +
                    "D 3\n" +
                    "R 11\n" +
                    "L 17\n" +
                    "U 7\n" +
                    "L 8\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "D 18\n" +
                    "L 16\n" +
                    "U 12\n" +
                    "D 16\n" +
                    "R 6\n" +
                    "U 16\n" +
                    "D 10\n" +
                    "R 1\n" +
                    "L 7\n" +
                    "U 18\n" +
                    "R 2\n" +
                    "U 13\n" +
                    "R 15\n" +
                    "D 1\n" +
                    "R 15\n" +
                    "D 9\n" +
                    "U 9\n" +
                    "R 15\n" +
                    "D 6\n" +
                    "L 14\n" +
                    "D 15\n" +
                    "R 15\n" +
                    "D 10\n" +
                    "U 15\n" +
                    "L 17\n" +
                    "D 12\n" +
                    "R 6\n" +
                    "L 1\n" +
                    "R 15\n" +
                    "L 7\n" +
                    "D 11\n" +
                    "R 12\n" +
                    "D 9\n" +
                    "L 17\n" +
                    "D 18\n" +
                    "L 19\n" +
                    "D 2\n" +
                    "L 9\n" +
                    "D 1\n" +
                    "L 7\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "U 19\n" +
                    "L 5\n" +
                    "U 2\n" +
                    "D 15\n" +
                    "L 10\n" +
                    "R 7\n" +
                    "L 18\n" +
                    "D 13\n" +
                    "R 2\n" +
                    "D 18\n" +
                    "U 8\n" +
                    "D 15\n" +
                    "U 14\n" +
                    "R 5\n" +
                    "L 9\n" +
                    "U 9\n" +
                    "D 18\n" +
                    "L 9\n" +
                    "U 6\n" +
                    "R 7\n" +
                    "L 10";
}
