package de.henry.adventofcode.y2022;

public class Day02 {

    public static final int LOOSE = 0;
    public static final int DRAW = 1;
    public static final int WIN = 2;

    public static final int ROCK = 1;
    public static final int PAPER = 2;
    public static final int SCISSORS = 3;


    public static void main(String[] args) {
        System.out.println("Score: " + calulateScore(INPUT, false));
        System.out.println("Score (Part 2): " + calulateScore(INPUT, true));
    }

    protected static int calulateScore(String input, boolean isPartTwo) {
        int score = 0;
        for (String l : input.split("\n")) {
            char you = l.charAt(0);
            char me = l.charAt(2);

            int youVal = you - 'A' + 1;
            int meVal = isPartTwo ? (calcMove(youVal, me - 'X')) : (me - 'X' + 1);
            int curScore = 3 * calcSingleScore(youVal, meVal);
            score += curScore + meVal;
        }
        return score;
    }

    private static int calcSingleScore(int youVal, int meVal) {
        if (youVal == meVal) {
            return DRAW;
        }
        if (youVal == ROCK) {
            return meVal == PAPER ? WIN : LOOSE;
        }
        if (youVal == PAPER) {
            return meVal == SCISSORS ? WIN : LOOSE;
        }
        if (youVal == SCISSORS) {
            return meVal == ROCK ? WIN : LOOSE;
        }
        return DRAW;
    }
    private static int calcMove(int youVal, int result) {
        if (result == DRAW) {
            return youVal;
        }
        if (youVal == PAPER) {
            return result == WIN ? SCISSORS : ROCK;
        }
        if (youVal == ROCK) {
            return result == WIN ? PAPER : SCISSORS;
        }
        if (youVal == SCISSORS) {
            return result == WIN ? ROCK : PAPER;
        }
        return youVal;
    }

    private static final String INPUT = "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "A Y\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "A Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "A Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "A Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z";
}
